### ISSUE TITLE
Configファイルの形式

### ISSUE THREAD

**Issue by harsssh** [smatsuodev/webserv-old#3]
パースが簡単な TOML を採用.
ただし, Table や Array は複数の表現方法があって嫌なので, 仕様通りにパーサーを実装するつもりはない.
```toml
error_page = { 404 = "/path/to/404.html" }
client_max_body_size = "10MB"

[[server]]
host = "127.0.0.1"
port = 8080
server_name = [ "example.com", "www.example.com" ]

	[[server.route]]
	path = "/"
	allowed_methods = [ "GET", "DELETE" ]
	root = "/var/www/html"
	autoindex = false
	index = "index.html"
	cgi_extensions = [ ".php", ".cgi" ]
	response_header = { Server = "Webserv" }

	[[server.route]]
	path = "/upload"
	allowed_methods = [ "POST" ]
	upload_path = "/var/uploads"

	[[server.route]]
	path = "/old-page"
	redirect = "/new_page"
```

### 機能要件
Mandatory
- [x] Choose the port and host of each ’server’
    - nginxのバーチャルサーバーに相当. listenするIP, ポートを `host`, `port` で指定できる.
- [x] Setup the server_names or not
    - `server_name` を指定できる.
- [x] Setup default error pages
    - `error_page` をステータスコードごとに指定できる.
- [x] Limit client body size
    - `client_max_body_size` を指定できる.
- [x] Define a list of accepted HTTP methods for the route
    - `allowed_methods` を指定できる.
- [x] Define a HTTP redirection
    - `redirect` を指定できる 
- [x] Define a directory or a file from where the file should be searched
    - `root` を指定できる.
- [x] Turn on or off directory listing
    - `autoindex` を指定できる. `autoindex = true` で有効.
- [x] Set a default file to answer if the request is a directory
    - `index` で指定できる.
- [x] Execute CGI based on certain file extension
    - `cgi_extensions` で指定できる.
- [x] Make the route able to accept uploaded files and configure where they should
be saved
   - Method, Content-Typeを見ればファイルアップロードかどうかを判断できる. 保存先は `upload_path` で指定する.

Bonus
- [x] Support cookies and session management
    - cookie は `response_header` で `Set-Cookie` を設定すれば実現できる.
    - "session management" も cookie を使えばできそう.
- [x] Handle multiple CGI
    - `cgi_extensions` は配列なので, 拡張子の異なる複数のCGIを実行できる.

### 補足
例の TOML は以下のJSONと (たぶん) 等価です.
```json
{
	"error_page": {
		"404": "/path/to/404.html"
	},
	"client_max_body_size": "10MB",
	"server": [
		{
			"host": "127.0.0.1",
			"port": 8080,
			"server_name": [ "example.com", "www.example.com" ],
			"route": [
				{
					"path": "/",
					"allowed_methods": [ "GET", "DELETE" ],
					"root": "/var/www/html",
					"autoindex": true,
					"index": "index.html",
					"cgi_extensions": [ ".php", ".cgi" ],
					"response_header": {
						"Server": "Webserv"
					}
				},
				{
					"path": "/upload",
					"allowed_methods": [ "POST" ],
					"upload_path": "/var/uploads"
				},
				{
					"path": "/old-page",
					"redirect": "/new-page"
				}
			]
		}
	]
}
```
