### ISSUE TITLE
設定ファイルの仕様を決める

### ISSUE THREAD

**Issue by smatsuodev** [smatsuodev/webserv-old#68]
# 概要
PBI: [#56](https://github.com/EringiShimeji/webserv/issues/56)

# タイムボックス
2day

# TODO
- [x] パースしやすい設定ファイルの仕様を決める
- [x] 実装の際に参考になる資料をまとめる
- [x] みんなに共有（レビュー）
- [x] 設定ファイルの仕様を[ここ](https://github.com/EringiShimeji/webserv/blob/e7e06df0051b751f5c4e6a170b300c4459a703f2/docs/config.md)にドキュメンテーション

**Comment by shmorish** [comment]
再帰下降法でC言語数式パーサーもどきを作ってみる
https://zenn.dev/nomunomu0504/articles/a8504ec7a18744

構文解析
https://qiita.com/hiro4669/items/8f3a7294bf7475f29b4b

あとでみる
https://www.youtube.com/watch?v=3Jp5TX-dbJQ&t=4998s

[toml parser]
https://in-neuro.hatenablog.com/entry/2018/12/14/160158
https://github.com/skystrife/cpptoml （C++11）
https://github.com/ToruNiina/toml11 （C++11）

[yaml parser]
https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.5.3 （does not require C++11）

ファイル形式比較
```
TOML、JSON : 設定ファイルや簡単なデータ表現
XML.      : より複雑な文書やデータを扱う
YAML      : 設定ファイルやデータのシリアライズに使われる
```

もりした的、yamlがよさそうに感じる。

**Comment by shmorish** [comment]
toml
```toml
error_page = { 404 = "/path/to/404.html" }
client_max_body_size = "10MB"

[[server]]
host = "127.0.0.1"
port = 8080
server_name = ["example.com", "www.example.com"]

[[server.route]]
path = "/"
allowed_methods = ["GET", "DELETE"]
root = "/var/www/html"
autoindex = false
index = "index.html"
cgi_extensions = [".php", ".cgi"]
response_header = { Server = "Webserv" }

[[server.route]]
path = "/upload"
allowed_methods = ["POST"]
upload_path = "/var/uploads"

[[server.route]]
path = "/old-page"
redirect = "/new_page"
```
↓
yaml
```yaml
error_page:
  '404': "/path/to/404.html"
client_max_body_size: "10MB"

server:
  - host: "127.0.0.1"
    port: 8080
    server_name:
      - "example.com"
      - "www.example.com"
    route:
      - path: "/"
        allowed_methods: ["GET", "DELETE"]
        root: "/var/www/html"
        autoindex: false
        index: "index.html"
        cgi_extensions: [".php", ".cgi"]
        response_header:
          Server: "Webserv"
      - path: "/upload"
        allowed_methods: ["POST"]
        upload_path: "/var/uploads"
      - path: "/old-page"
        redirect: "/new_page"
```
