### ISSUE TITLE
Codecovの設定を見直したい

### ISSUE THREAD

**Issue by harsssh** [smatsuodev/webserv-old#88]
# 実現したいこと

Codecovの設定を見直したい。なぜならカバレッジの情報が見やすく・扱いやすくなるからだ。

見た目以外にも、以下の設定ができるのでやりたい。
- カバレッジの変更がなければPRに差分を表示しない
- 他のCIの実行結果を待たない
- カバレッジが下がっても Codecov のステータスチェックが通るようにする。
- File Changes への注釈をしない

こんな感じでできるはずだが、うまくいかなかった。
```yaml
ignore:
  - "cmd/"
  - "tests/"
comment:
  # Show the comment only on coverage changes
  require_changes: true
  layout: "reach, files, diff"
coverage:
  # Show the Codecov status without waiting for other status checks to complete or pass
  require_ci_to_pass: false
  status:
    project:
      default:
        # See status checks but prevent them from blocking
        informational: true
    patch:
      default:
        informational: true
github_checks:
  annotations: false
```

# AC（受け入れ条件）

- `codecov.yml` に上記の設定を反映する

# TODO

- [ ] `codecov.yml` の編集
- [ ] レビュー
- [ ] マージ
